sudo: required 
services:
  - docker
  
script:
  - docker build -t jldroid25/docker-github-travis-pipeline .
  - docker images DockerGithubTravisPipeline
    # Create these Login Variables in your app TravisCi's setting 
    # with your Docker-Hub login's credentiol(Not Github login credential)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  
before_deploy: 

deploy:
  provider: script
  script: docker push jldroid25/docker-github-travis-pipeline
  on:
    branch:
      only:
        - master