sudo: required 
services:
  - docker
  
script:
  - docker build -t jldroid25/docker-github-travis-pipeline .
  - docker images DockerGithubTravisPipeline
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  
before_deploy: 

deploy:
  provider: script
  script: docker push jldroid25/docker-github-travis-pipeline
  on:
    branch: main